### ISSUE TITLE
Review items

### ISSUE THREAD

**Issue by desktophero** [target/sccmosd-refresh-multitool#1]
For brand protection, I'd like to get some clarification on this item:
- [ ] Do any of the Windows or Dell names or products need appropriate copyright/trademark/links? Since this is a Target branded repo, there should be some attention to the branding of other companies in our doc.

For technical content, I'm 👍 with shipping it. The items below can be managed through other issues/conversations.
- [ ] Probably a bit pedantic, but the class prefixed with `TGT` won't be relevant to other companies or persons wanting to use this. Would a [more generic name](https://github.com/target/sccmosd-refresh-multitool/blob/master/TaskSequence/DeploymentToolkit/Scripts/RMTRefreshPC.wsf#L33) make sense or just overkill? 
- [ ] Does this process require [SCCM](https://github.com/target/sccmosd-refresh-multitool/blob/master/WinPE/Create-RefreshMultiToolBootWIM.ps1#L110)? 
- [ ] Does any of the Dell BIOS (`cctk`) configs/code fall under Dell's software [licensing](http://www.dell.com/learn/us/en/19/solutions/software-license-agreements?c=us&l=en&s=dhs&cs=19&~mode=popup)? I read through and nothing jumped out with concerns - we're not redistributing other company code.
- [ ] How would a consumer of this trying it out test their local changes? Is there a test harness that either shows the changes are working correctly or the like - unit or functional tests?
- [ ] Add a section to the root `README` that defines all the requirements for the repo (WinPE, flash drive, downloads and versions used to create the process)

**Comment by mikebeckel** [comment]
- [x] Probably a bit pedantic, but the class prefixed with `TGT` won't be relevant to other companies or persons wanting to use this. Would a [more generic name](https://github.com/target/sccmosd-refresh-multitool/blob/master/TaskSequence/DeploymentToolkit/Scripts/RMTRefreshPC.wsf#L33) make sense or just overkill?
  _Updated_
- [x] Does this process require [SCCM](https://github.com/target/sccmosd-refresh-multitool/blob/master/WinPE/Create-RefreshMultiToolBootWIM.ps1#L110)? 
  _Yes, I added a requires section to the main ReadMe.md_
- [x] Does any of the Dell BIOS (`cctk`) configs/code fall under Dell's software [licensing](http://www.dell.com/learn/us/en/19/solutions/software-license-agreements?c=us&l=en&s=dhs&cs=19&~mode=popup)? I read through and nothing jumped out with concerns - we're not redistributing other company code.
  _We're not distributing any of their code or binaries so we're fine._
- [x] How would a consumer of this trying it out test their local changes? Is there a test harness that either shows the changes are working correctly or the like - unit or functional tests?
  _Almost every script in this process is destructive so they can't be tested without running through the entire process_
- [x] Add a section to the root `README` that defines all the requirements for the repo (WinPE, flash drive, downloads and versions used to create the process)
  _Complete_
