### ISSUE TITLE
Looks like  - RMT_LTIApply.wsf is missing

### ISSUE THREAD

**Issue by ThumbsUpCode** [target/sccmosd-refresh-multitool#3]
Looks like  - RMT_LTIApply.wsf is missing

**Comment by mikebeckel** [comment]
It's not missing. I wasn't sure if we could redistribute Microsoft code so we left it up to you to download MDT and modify the file. 

RMT_LTIApply.wsf is based on LTIApply.wsf which is included with the MDT Deployment Toolkit. The only modification to the file is the removal of the /mbr parameter on the bootsect.exe command. You are responsible for making this update in your Deployment Toolkit package.

Here's what the line looks like after removing the /mbr command. 

``` vbscript
oLogging.CreateEntry "Executing BOOTSECT.EXE to install a Vista boot sector", LogTypeInfo
iRC = oUtility.FindExeAndRunWithLogging( "bootsect.exe", "/nt60 " & sBootDrive)
```

**Comment by ThumbsUpCode** [comment]
Thanks, That made sense. I overlooked couple of words though, I m still testing it.

**Comment by jgeater** [comment]
I'm running into a slightly different problem. I made the modification but the script is returning the "Class not defined"
Here are the log entries.

---

Property LogPath is now = C:\Windows\CCM\Logs\SMSTSLog  RMT_LTIApply    10/25/2016 7:33:09 AM   0 (0x0000)
Property pe is now =    RMT_LTIApply    10/25/2016 7:33:09 AM   0 (0x0000)
Microsoft Deployment Toolkit version: 6.3.8330.1000 RMT_LTIApply    10/25/2016 7:33:09 AM   0 (0x0000)
The task sequencer log is located at C:\Windows\CCM\Logs\SMSTSLog\SMSTS.LOG.  For task sequence failures, please consult this log.  RMT_LTIApply    10/25/2016 7:33:09 AM   0 (0x0000)
Property Debug is now = FALSE   RMT_LTIApply    10/25/2016 7:33:09 AM   0 (0x0000)
FAILURE (Err): 506: Create object: Set oScriptClass = New RMT_LTIApply - Class not defined  RMT_LTIApply    10/25/2016 7:33:09 AM   0 (0x0000)
FAILURE ( 5400 ): Create object: Set oScriptClass = New RMT_LTIApply - Class not defined    RMT_LTIApply    10/25/2016 7:33:09 AM   0 (0x0000)

---

Any idea what I'm missing?

**Comment by ThumbsUpCode** [comment]
![rmt_ltiapply](https://cloud.githubusercontent.com/assets/20106897/19685711/897bf182-9adb-11e6-953b-00d281eee5b2.PNG)

You seem to be missing a building block of .wsf (ZTIUtil... vbs).   Find attached pic.

`<job id="RMT_LTIApply">
    <script language="VBScript" src="ZTIBCDUtility.vbs"/>
    <script language="VBScript" src="ZTIConfigFile.vbs"/>
    <script language="VBScript" src="ZTIDiskUtility.vbs"/>
    <script language="VBScript" src="ZTIUtility.vbs"/>
    <script language="VBScript">

' // ***************************************************************************
' // 
' // Copyright (c) Microsoft Corporation.  All rights reserved.
' // 
' // Microsoft Deployment Toolkit Solution Accelerator
' //
' // File:      RMT_LTIApply.wsf
' // 
' // Version:   6.3.8298.1000
' // 
' // Purpose:   Apply image (OS or PE) to the hard drive
' // 
' // Usage:     cscript.exe [//nologo] RMT_LTIApply.wsf [/debug:true] [/pe] [/post]
' // 
' // ***************************************************************************

Option Explicit
RunNewInstance

'//----------------------------------------------------------------------------
'//  Main Class
'//----------------------------------------------------------------------------

Class RMT_LTIApply`

**Comment by jgeater** [comment]
That did the trick. 
thanks

**Comment by ThumbsUpCode** [comment]
You seem to be missing a building block of .wsf (ZTIUtil... vbs).  Moreover, attached script for reference.

[https://attachment.outlook.office.net/owa/Chandan.k.Sharma@hotmail.com/service.svc/s/GetFileAttachment?id=AQMkADAwATZiZmYAZC1hZTgxLWM2YzItMDACLTAwCgBGAAADI8QNlWa2n0a59ZQUmjRrcAcAX7yKOArJhkmSKD1rFQZJvgAAAgEPAAAAX7yKOArJhkmSKD1rFQZJvgAAACLDuegAAAABEgAQACdYMidIwUVFAIlSikXvXmYa&X-OWA-CANARY=QAPwsAIkOUKhU6nAYN7DPCAi6vHO_NMYuDDrPs53PweFusIfS_p4fNbvKKYNSKzPcl0XHjkLBxA.&token=14191959-e315-4387-8d36-d5d2475f781b&owa=outlook.live.com&isc=1]

Regards,
